In [2]:
import torch

#### Tensors

##### Torch.rand cria tensors com tamanho no formato Rn, torch zeros faz o mesmo porem com todos os numeros do tensor iguais a zero e o torch.ones mesma coisa porem com os numeros iguais a 1, o _like no final do tensor faz o tensor chamado anteriormente do _like (Ex: torch.zeros_like) fara um tensor de zeros no tamanho passado como argumento para a função

In [21]:
t1 = torch.rand(2)
print(t1, "\n")
t2 = torch.rand(2, 2)
print(t2, "\n")
t3 = torch.rand(2, 2, 2)
print(t3)

tz = torch.zeros(2, 2)
tz

tone = torch.ones(2, 2)
tone


t4 = torch.zeros_like(tone)
t4

tensor([0.1754, 0.4059]) 

tensor([[0.7931, 0.9895],
        [0.1662, 0.4423]]) 

tensor([[[0.4409, 0.0964],
         [0.7076, 0.6130]],

        [[0.8625, 0.8712],
         [0.7886, 0.4800]]])


tensor([[0., 0.],
        [0., 0.]])

### Pegando informacoes de tensors - Tensor atributes -
1. Tensor no datatype errado - pra pegar o dtype de um tensor, usar `tensor.dtype`
2. Tensor no shape errado - pra pegar o shape de um tensor, usar `tensor.shape`
3. Tensor no device errado - pra pegar o device de um  tensor, usar `tensor.device`

In [29]:
tensor1 = torch.rand(3, 3)
print(tensor1.dtype)
print(tensor1.shape)
print(tensor1.device)

torch.float32
torch.Size([3, 3])
cpu


#### Multiplicacao de matrizes

##### torch.mm realiza a multiplicacao de matrizes, e .T transorma a matriz em sua matrix transposta

In [31]:
t1 = torch.rand(3, 4)
t2 = torch.rand(4, 6)
value = torch.mm(t1, t2)
value

t1.T

tensor([[0.5854, 0.4174, 0.4355],
        [0.3706, 0.1801, 0.4490],
        [0.4125, 0.2194, 0.5974],
        [0.1756, 0.6629, 0.4791]])

#### Achar o min, max, mean, sum, etc (tensor aggregation)

In [37]:
x = torch.arange(0, 100, 10).type(torch.float16) # Tensor aggregation nao aceita tipos long
print(x)
print(torch.min(x))
print(torch.max(x))
print(torch.mean(x))
print(torch.sum(x))


print(x.argmin())
print(x.argmax())

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)
tensor(0., dtype=torch.float16)
tensor(90., dtype=torch.float16)
tensor(45., dtype=torch.float16)
tensor(450., dtype=torch.float16)
tensor(0)
tensor(9)


##### Criando tensores numa range

In [4]:
tr = torch.arange(start=0, end=100, step=10)
print(tr)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


##### Reshaping, stacking, squeezing e unsqueezing

In [ ]:
t1 = torch.rand(2, 3, 3)
print("Before: ",t1)
t1 = t1.reshape(9, 2)
print("After: ",t1)
t2 = t1.view(3, 3, 2)  # T2 é um ponteiro alterado do T1, se mudar os numeros presentes em T1, os numeros de T2 tambem serão alterados
t1_stacked = torch.stack((t1, t1), dim=0) # Dimensao 0 é o eixo Y (Coloca um em cima do outro)
print("\n Stacked: ",t1_stacked, t1_stacked.shape)

Before:  tensor([[[0.4890, 0.3215, 0.1244],
         [0.6906, 0.4878, 0.3437],
         [0.3187, 0.5026, 0.2887]],

        [[0.7601, 0.2356, 0.0890],
         [0.5191, 0.3912, 0.4934],
         [0.6528, 0.9471, 0.5395]]])
After:  tensor([[0.4890, 0.3215],
        [0.1244, 0.6906],
        [0.4878, 0.3437],
        [0.3187, 0.5026],
        [0.2887, 0.7601],
        [0.2356, 0.0890],
        [0.5191, 0.3912],
        [0.4934, 0.6528],
        [0.9471, 0.5395]])

 Stacked:  tensor([[[0.4890, 0.3215],
         [0.1244, 0.6906],
         [0.4878, 0.3437],
         [0.3187, 0.5026],
         [0.2887, 0.7601],
         [0.2356, 0.0890],
         [0.5191, 0.3912],
         [0.4934, 0.6528],
         [0.9471, 0.5395]],

        [[0.4890, 0.3215],
         [0.1244, 0.6906],
         [0.4878, 0.3437],
         [0.3187, 0.5026],
         [0.2887, 0.7601],
         [0.2356, 0.0890],
         [0.5191, 0.3912],
         [0.4934, 0.6528],
         [0.9471, 0.5395]]]) torch.Size([2, 9, 2])


##### Squeeze e unsqueeze tirando e colocam dimensois unicas no tensor


In [24]:
t1 = torch.rand(1, 1, 2)
print(t1, t1.shape)
t1 = t1.squeeze()
print(t1, t1.shape)

tensor([[[0.3543, 0.0530]]]) torch.Size([1, 1, 2])
tensor([0.3543, 0.0530]) torch.Size([2])


In [30]:
t1 = torch.rand(3)
print(t1, t1.shape)

t1_un0 = t1.unsqueeze(dim=0)
print(t1_un0, t1_un0.shape)

t1_un1 = t1.unsqueeze(dim=1)
print(t1_un1, t1_un1.shape)

tensor([0.1321, 0.7067, 0.5171]) torch.Size([3])
tensor([[0.1321, 0.7067, 0.5171]]) torch.Size([1, 3])
tensor([[0.1321],
        [0.7067],
        [0.5171]]) torch.Size([3, 1])
